/**
 * draft_email — Drafts an email and saves it as a markdown file in the vault.
 *
 * This simulates sending an email by writing the draft to a file.
 * In Silver tier, this would connect to a real SMTP/Gmail API.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

export const definition = {
  name: "draft_email",
  description:
    "Draft an email and save it to the vault for review. " +
    "The email is saved as a markdown file, not actually sent (Bronze mode).",
  inputSchema: {
    type: "object",
    properties: {
      to: {
        type: "string",
        description: "Recipient email address",
      },
      subject: {
        type: "string",
        description: "Email subject line",
      },
      body: {
        type: "string",
        description: "Email body content (plain text or markdown)",
      },
      vault_path: {
        type: "string",
        description: "Path to the vault root directory",
        default: "./vault",
      },
    },
    required: ["to", "subject", "body"],
  },
};

export async function handler({ to, subject, body, vault_path }) {
  // Validate inputs
  if (!to || !subject || !body) {
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            success: false,
            error: "Missing required fields: to, subject, body",
          }),
        },
      ],
    };
  }

  const vaultRoot = vault_path || "./vault";
  const draftsDir = join(vaultRoot, "drafts");
  const now = new Date();
  const timestamp = now.toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const slug = subject
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 40);
  const filename = `${timestamp}_${slug}.md`;
  const filepath = join(draftsDir, filename);

  // Build the email draft as markdown
  const content = `---
type: email-draft
to: "${to}"
subject: "${subject}"
created: "${now.toISOString()}"
status: draft
---

# Email Draft

**To:** ${to}
**Subject:** ${subject}
**Date:** ${now.toISOString().slice(0, 10)}

---

${body}

---
*Draft generated by AI Employee (Bronze Mode) — not yet sent*
`;

  try {
    mkdirSync(draftsDir, { recursive: true });
    writeFileSync(filepath, content, "utf-8");

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            success: true,
            message_id: `draft-${timestamp}`,
            file: filepath,
            preview: `To: ${to} | Subject: ${subject} | ${body.slice(0, 80)}...`,
          }),
        },
      ],
    };
  } catch (err) {
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            success: false,
            error: `Failed to write draft: ${err.message}`,
          }),
        },
      ],
    };
  }
}
