"""AI bridge — interface to Cohere API for reasoning.

Uses the Cohere Python SDK to generate plans and review results.
Falls back to simulated responses if COHERE_API_KEY is not set
or the API call fails.
"""

import logging
import os
import time
from pathlib import Path

from orchestrator.config import config

logger = logging.getLogger("orchestrator.ai")

_PROMPTS_DIR = Path(__file__).parent / "prompts"

# ── Cohere client initialization ──────────────────────────────────────────────

_cohere_client = None
_simulation_mode = False

try:
    import cohere

    _api_key = os.getenv("COHERE_API_KEY", "")
    if _api_key:
        _cohere_client = cohere.ClientV2(api_key=_api_key)
        logger.info("Cohere client initialized successfully")
    else:
        _simulation_mode = True
        logger.warning(
            "COHERE_API_KEY not set — running in simulation mode"
        )
except ImportError:
    _simulation_mode = True
    logger.warning(
        "cohere package not installed — running in simulation mode"
    )


# ── Prompt helpers ────────────────────────────────────────────────────────────


def _load_prompt(name: str) -> str:
    """Load a prompt template from the prompts directory."""
    path = _PROMPTS_DIR / name
    return path.read_text(encoding="utf-8")


def _load_context() -> tuple[str, str]:
    """Load user context and tools registry from the vault."""
    context_dir = config.vault.context

    user_context = ""
    profile_path = context_dir / "user-profile.md"
    if profile_path.exists():
        user_context = profile_path.read_text(encoding="utf-8")

    tools_registry = ""
    tools_path = context_dir / "tools-registry.md"
    if tools_path.exists():
        tools_registry = tools_path.read_text(encoding="utf-8")

    return user_context, tools_registry


def _build_planning_prompt(task_body: str) -> str:
    """Build the full prompt for the AI to generate a task plan."""
    system_prompt = _load_prompt("system.md")
    plan_template = _load_prompt("plan_task.md")
    user_context, tools_registry = _load_context()

    prompt = plan_template.replace("{task_content}", task_body)
    prompt = prompt.replace(
        "{user_context}", user_context or "(No user profile configured)"
    )
    prompt = prompt.replace(
        "{tools_registry}", tools_registry or "(No tools registered)"
    )

    return f"{system_prompt}\n\n---\n\n{prompt}"


# ── Core API call ─────────────────────────────────────────────────────────────


def call_ai(prompt: str, max_tokens: int | None = None) -> str:
    """Call the Cohere API and return the response text.

    Falls back to a simulated response if the API key is missing
    or the SDK is unavailable.
    """
    if _simulation_mode or _cohere_client is None:
        logger.warning("Cohere API unavailable — using simulated response")
        return _simulate_response(prompt)

    tokens = max_tokens or config.claude.max_tokens

    logger.info("Calling Cohere API for reasoning...")
    start = time.time()

    try:
        response = _cohere_client.chat(
            model="command-r-plus",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=tokens,
        )

        elapsed_ms = int((time.time() - start) * 1000)

        # Extract text from the response
        result_text = ""
        if response.message and response.message.content:
            for block in response.message.content:
                if hasattr(block, "text"):
                    result_text += block.text

        if not result_text:
            logger.warning("Cohere returned empty response — using simulation")
            return _simulate_response(prompt)

        logger.info(
            f"Cohere responded ({elapsed_ms}ms, {len(result_text)} chars)"
        )
        return result_text

    except Exception as e:
        logger.error(f"Cohere API error: {e} — falling back to simulation")
        return _simulate_response(prompt)


# ── Simulation fallback ──────────────────────────────────────────────────────


def _simulate_response(prompt: str) -> str:
    """Generate a simulated response when the AI API is unavailable.

    This allows testing the full orchestrator flow without an API key.
    """
    logger.info("  (Using simulated AI response for demo)")

    return """## Proposed Plan

- [ ] Step 1: Read task request and understand requirements (tool: none, approval: no)
- [ ] Step 2: Gather relevant context from vault (tool: none, approval: no)
- [ ] Step 3: Draft the requested output (tool: draft_email, approval: yes)
- [ ] Step 4: Present draft for human review (tool: none, approval: no)

## Draft Output

Subject: Task Completed — AI Employee Report

Dear Team,

This is an automated draft generated by the AI Employee system.
The task has been analyzed and a draft has been prepared for your review.

Please review the proposed plan above and approve or reject in Obsidian.

Best regards,
AI Employee (Bronze Mode)

---
*Generated by Personal AI Employee — awaiting human approval*"""


# ── Public API ────────────────────────────────────────────────────────────────


def generate_plan(task_body: str) -> str:
    """Generate a plan for a task using AI reasoning.

    Args:
        task_body: The markdown body of the task file.

    Returns:
        The plan text (markdown) to be written into the task file.
    """
    prompt = _build_planning_prompt(task_body)
    return call_ai(prompt)


def review_result(task_body: str, action: str, result: str) -> str:
    """Ask the AI to verify an action result.

    Returns the AI's verification response.
    """
    template = _load_prompt("review_result.md")
    prompt = template.replace("{task_content}", task_body)
    prompt = prompt.replace("{action_description}", action)
    prompt = prompt.replace("{action_result}", result)
    return call_ai(prompt)
