"""Claude bridge — interface to Claude Code CLI for reasoning.

Shells out to the `claude` CLI with structured prompts built
from templates and task context. Parses the response into
actionable plan text.
"""

import logging
import subprocess
import time
from pathlib import Path

from orchestrator.config import config

logger = logging.getLogger("orchestrator.claude")

_PROMPTS_DIR = Path(__file__).parent / "prompts"


def _load_prompt(name: str) -> str:
    """Load a prompt template from the prompts directory."""
    path = _PROMPTS_DIR / name
    return path.read_text(encoding="utf-8")


def _load_context() -> tuple[str, str]:
    """Load user context and tools registry from the vault."""
    context_dir = config.vault.context

    user_context = ""
    profile_path = context_dir / "user-profile.md"
    if profile_path.exists():
        user_context = profile_path.read_text(encoding="utf-8")

    tools_registry = ""
    tools_path = context_dir / "tools-registry.md"
    if tools_path.exists():
        tools_registry = tools_path.read_text(encoding="utf-8")

    return user_context, tools_registry


def _build_planning_prompt(task_body: str) -> str:
    """Build the full prompt for Claude to generate a task plan."""
    system_prompt = _load_prompt("system.md")
    plan_template = _load_prompt("plan_task.md")
    user_context, tools_registry = _load_context()

    prompt = plan_template.replace("{task_content}", task_body)
    prompt = prompt.replace("{user_context}", user_context or "(No user profile configured)")
    prompt = prompt.replace("{tools_registry}", tools_registry or "(No tools registered)")

    return f"{system_prompt}\n\n---\n\n{prompt}"


def call_claude(prompt: str, max_tokens: int | None = None) -> str:
    """Call the Claude CLI and return the response text.

    Uses `claude -p` (print mode) for non-interactive single-shot prompts.
    Falls back to a simulated response if the CLI is not available.
    """
    tokens = max_tokens or config.claude.max_tokens

    logger.info("Calling Claude for reasoning...")
    start = time.time()

    try:
        result = subprocess.run(
            ["claude", "-p", "--max-tokens", str(tokens), prompt],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(config.vault.root),
        )

        elapsed_ms = int((time.time() - start) * 1000)

        if result.returncode != 0:
            stderr = result.stderr.strip()
            logger.warning(f"Claude CLI returned code {result.returncode}: {stderr}")
            # Fall through to check if we got stdout anyway
            if not result.stdout.strip():
                raise RuntimeError(f"Claude CLI error: {stderr}")

        response = result.stdout.strip()
        logger.info(f"Claude responded ({elapsed_ms}ms, {len(response)} chars)")
        return response

    except FileNotFoundError:
        logger.warning("Claude CLI not found — using simulated response")
        return _simulate_response(prompt)
    except subprocess.TimeoutExpired:
        logger.error("Claude CLI timed out after 120s")
        raise RuntimeError("Claude CLI timed out")


def _simulate_response(prompt: str) -> str:
    """Generate a simulated response when Claude CLI is unavailable.

    This allows testing the full orchestrator flow without the CLI.
    """
    logger.info("  (Using simulated AI response for demo)")

    return """## Proposed Plan

- [ ] Step 1: Read task request and understand requirements (tool: none, approval: no)
- [ ] Step 2: Gather relevant context from vault (tool: none, approval: no)
- [ ] Step 3: Draft the requested output (tool: draft_email, approval: yes)
- [ ] Step 4: Present draft for human review (tool: none, approval: no)

## Draft Output

Subject: Task Completed — AI Employee Report

Dear Team,

This is an automated draft generated by the AI Employee system.
The task has been analyzed and a draft has been prepared for your review.

Please review the proposed plan above and approve or reject in Obsidian.

Best regards,
AI Employee (Bronze Mode)

---
*Generated by Personal AI Employee — awaiting human approval*"""


def generate_plan(task_body: str) -> str:
    """Generate a plan for a task using Claude reasoning.

    Args:
        task_body: The markdown body of the task file.

    Returns:
        The plan text (markdown) to be written into the task file.
    """
    prompt = _build_planning_prompt(task_body)
    return call_claude(prompt)


def review_result(task_body: str, action: str, result: str) -> str:
    """Ask Claude to verify an action result.

    Returns Claude's verification response.
    """
    template = _load_prompt("review_result.md")
    prompt = template.replace("{task_content}", task_body)
    prompt = prompt.replace("{action_description}", action)
    prompt = prompt.replace("{action_result}", result)
    return call_claude(prompt)
